# Generated by Django 3.1.3 on 2020-12-14 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newslist',
            old_name='creator',
            new_name='user',
        ),
    ]
