# Generated by Django 3.1.3 on 2020-12-17 23:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_plaidauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='plaidauth',
            name='item_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plaidauth',
            name='access_token',
            field=models.CharField(max_length=100),
        ),
    ]
