# Generated by Django 3.1.3 on 2020-12-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0005_stocklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='author',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
