# Generated by Django 3.1.3 on 2020-12-21 22:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0006_auto_20201221_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='author',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1, message='This field cannot be blank')]),
        ),
    ]
